"""
Crosses RFM segments with payment failure rates and CLV to answer the
question a product team actually cares about: not just "which segment fails
the most," but "which failures are sitting behind the most money."

A segment with a 20% decline rate is not automatically the priority. A small,
low-value segment with a bad decline rate matters less than a large,
high-value segment with a moderately bad one. So the core metric here is
value-weighted failure exposure: total CLV held in a segment multiplied by
that segment's failure rate. It estimates how much lifetime value is
currently sitting behind transactions that are failing at an elevated rate.

Recommendations are generated by ranking on that metric, not hardcoded, so
the output changes honestly if the underlying data changes.
"""

import pandas as pd


def compute_segment_failure_rates(transactions: pd.DataFrame, clv: pd.DataFrame) -> pd.DataFrame:
    txn_with_segment = transactions.merge(
        clv[["merchant_id", "segment"]], on="merchant_id", how="left"
    )

    grouped = txn_with_segment.groupby("segment").agg(
        total_transactions=("transaction_id", "count"),
        failed_transactions=("status", lambda s: (s == "Failed").sum()),
    ).reset_index()

    grouped["failure_rate"] = grouped["failed_transactions"] / grouped["total_transactions"]
    return grouped


def build_segment_summary(clv: pd.DataFrame, transactions: pd.DataFrame) -> pd.DataFrame:
    failure_rates = compute_segment_failure_rates(transactions, clv)

    segment_value = clv.groupby("segment").agg(
        merchant_count=("merchant_id", "count"),
        avg_clv=("total_clv", "mean"),
        total_clv=("total_clv", "sum"),
        avg_recency_days=("recency_days", "mean"),
    ).reset_index()

    summary = segment_value.merge(failure_rates, on="segment", how="left")

    overall_failure_rate = transactions["status"].eq("Failed").mean()
    summary["platform_avg_failure_rate"] = overall_failure_rate
    summary["failure_rate_vs_platform"] = summary["failure_rate"] - overall_failure_rate

    # Dollar value of lifetime value sitting behind a segment's current decline rate.
    summary["value_weighted_failure_exposure"] = summary["total_clv"] * summary["failure_rate"]

    return summary.sort_values("value_weighted_failure_exposure", ascending=False).reset_index(drop=True)


def generate_recommendations(summary: pd.DataFrame, top_n: int = 2) -> list[dict]:
    """
    Recommendation 1: among segments worth retaining (Champions, Loyal, At
    Risk), the one with the highest value-weighted failure exposure, RESTRICTED
    to segments whose failure rate is actually above the platform average.
    A segment can rank high on raw exposure just because it is large, even if
    its failure rate is fine, and that is not a failure problem worth flagging.

    Recommendation 2: the highest-value segment among "At Risk" specifically,
    since that segment already shows the recency drop-off pattern of churn in
    progress. If its failure rate is also above the platform average, elevated
    declines are a plausible contributor to why they went quiet, not proof of
    it, but a strong enough signal to justify a targeted retention action.
    """
    recommendations = []

    retain_segments = summary[
        summary["segment"].isin(["Champions", "Loyal", "At Risk"])
        & (summary["failure_rate"] > summary["platform_avg_failure_rate"])
    ]
    if not retain_segments.empty:
        top_exposure = retain_segments.iloc[0]
        recommendations.append({
            "title": f"Fix payment failures in {top_exposure['segment']} first",
            "detail": (
                f"{top_exposure['segment']} holds ${top_exposure['total_clv']:,.0f} in total lifetime "
                f"value across {int(top_exposure['merchant_count'])} merchants, with a failure rate of "
                f"{top_exposure['failure_rate']:.1%} against a platform average of "
                f"{top_exposure['platform_avg_failure_rate']:.1%}. That is "
                f"${top_exposure['value_weighted_failure_exposure']:,.0f} of lifetime value currently "
                f"sitting behind an elevated decline rate. Reducing declines here (retry logic, updated "
                f"card details, smarter routing) protects more revenue per percentage point improved than "
                f"doing the same work in a lower-value segment."
            ),
        })

    at_risk = summary[summary["segment"] == "At Risk"]
    if not at_risk.empty:
        row = at_risk.iloc[0]
        above_avg = row["failure_rate"] > row["platform_avg_failure_rate"]
        recommendations.append({
            "title": "Treat At Risk as a churn-prevention priority, not just a monitoring segment",
            "detail": (
                f"At Risk merchants have already gone quiet (average {row['avg_recency_days']:.0f} days "
                f"since last transaction) despite carrying real historic value "
                f"(${row['total_clv']:,.0f} total, ${row['avg_clv']:,.0f} average per merchant). "
                + (
                    f"Their failure rate of {row['failure_rate']:.1%} is above the platform average of "
                    f"{row['platform_avg_failure_rate']:.1%}, which is consistent with payment friction "
                    f"being part of why they stopped transacting, not just demand dropping off. "
                    if above_avg else
                    f"Their failure rate of {row['failure_rate']:.1%} is not above the platform average, "
                    f"so the drop-off looks more like a demand or competitive issue than a payments problem. "
                )
                + "Either way, this segment still holds recoverable value and should get a direct "
                  "win-back outreach before it fully cools into Dormant."
            ),
        })

    return recommendations[:top_n]
